### ISSUE TITLE
登陆提示密码错误

### ISSUE THREAD

**Issue by linjinxiu** [linyuchen/WebQQSDK#1]
登陆的时候提示错误，确认了很多次，保证没有输入错误。登录失败 ptuiCB('3','0','','0','您输入的帐号或密码不正确，请重新输入。', '541441151');

**Comment by linyuchen** [comment]
先去WebQQ官网登陆看看能不能登陆，如果不能登陆有可能是账号问题，然后再换个账号试试程序登陆
