### ISSUE TITLE
请问一下, 发送消息的功能目前实现了吗?

### ISSUE THREAD

**Issue by zhanglintc** [linyuchen/WebQQSDK#3]
是不是还要自己继续开发? 能往群里发消息吗?

**Comment by linyuchen** [comment]
收发消息api都已实现，能往群里发消息的

**Comment by zhanglintc** [comment]
发消息和发群消息是哪个函数呢? 还有就是这个协议的话, 是自己分析的, 还是webqq有官方的接口提供? 我好像没找到官方的网站.

**Comment by linyuchen** [comment]
api函数在doc文件夹的文档都有说明，协议自己分析的








发件人: Lane
发送时间: ‎2015‎年‎2‎月‎28‎日 ‎星期六 ‎‎18‎:‎21
收件人: linyuchen/WebQQSDK
抄送: yuchen lin





发消息和发群消息是哪个函数呢? 还有就是这个协议的话, 是自己分析的, 还是webqq有官方的接口提供? 我好像没找到官方的网站.
