### ISSUE TITLE
关于登录验证码的问题

### ISSUE THREAD

**Issue by Hurray0** [linyuchen/WebQQSDK#4]
??????֤??:mycx
登录失败 ptuiCB('4','0','','0','您输入的验证码不正确，请重新输入。', '184333969');

如上，我按照图片里验证码输入以后一直报错，无法正常登录，请问一下是什么问题呢？

如果可以的话可以邮件联系我me@hurray0.com

**Comment by linyuchen** [comment]
官网协议已经更新了，我没有同步更新，暂时登录不了
